Error
After merging your changes from yesterday it didn't work anymore.
Removed a * because of the following error:

Traceback (most recent call last):
File "volvooncall.py", line 86, in <module>
res, value = Connection(**credentials()).update()
TypeError: Connection constructor argument after ** must be a mapping,
not list

NOTE; loading credentials from yaml file has never worked for me (will
post a bug too)